package com.covenant_scholar.learning_scroll_server.assessment.entity;

public enum SkillCategory {

	BASIC_COMPREHENSION, 
	VOCABULARY_AND_LANGUAGE, 
	INTERPRETATION_AND_INFERENCE, 
	CRITICAL_THINKING_AND_ANALYSIS,
	TEXT_STRUCTURE_AND_LITERARY_ANALYSIS, 
	SYNTHESIS_AND_APPLICATION, 
	BIBLICAL_CONNECTIONS;
}
